### ISSUE TITLE
Setup Docker environment

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#1]
We should use Ruby image (debian is easier) and Postgres.

- [x] Dockerfile
- [x] docker-compose.yml

**Comment by mlan080** [comment]
**Steps for Mandy**
Create a docker file https://hub.docker.com/_/ruby/
Create a docker-compose.yaml then run docker-compose build so we have configuration set up and don't need to write from scratch as with docker build -t tea shops

**Comment by lucasrenan** [comment]
https://github.com/mlan080/tea-shops/pull/13
