### ISSUE TITLE
Add validations to Shop model

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#12]
Add a `valid?` method to check the presence of
- name
- description

when the object is not valid, it should respond to a method`errors` which returns an array of error messages (simple strings).

**Comment by lucasrenan** [comment]
@mlan080 task description updated

**Comment by mlan080** [comment]
Cases 
1. When shop is valid, we expect valid return to be true and error empty
2. When shop is not valid, return the error message #{shop.errors}
