### ISSUE TITLE
Add a Ruby hello world script

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#2]
Simple ruby script to show that everything works.

**Comment by mlan080** [comment]
**Alex exercises**
- Add Helloworld.rb to your image through Dockerfile
- Override the CMD and use it to run Helloworld.rb script

**Expected result**
'Docker run [image name]' will render "hello world"

**Comment by lucasrenan** [comment]
https://github.com/mlan080/tea-shops/pull/13
