### ISSUE TITLE
Add missing specs for count

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#30]
https://github.com/mlan080/tea-shops/blob/master/app/models/shop.rb#L17

**Comment by mlan080** [comment]
Do you mean something like this? 


 describe "#count" do
    let(:rows) { DB[:shops].count }

    it 'counts number of rows in database' do
      expect(Shop.count).to eq(rows)
    end
  end

**Comment by lucasrenan** [comment]
maybe more like inserting two shops in the database and them checking `expect(Shop.count).to eq(2)`
