### ISSUE TITLE
Configure RSpec

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#4]
- [x] `rspec` gem should be added as a dependency using `bundler` (Gemfile) within Dockerfile
- [x] Get RSpec running with `Shop` model, like `spec/models/shop_spec.rb`.
- [x] Just as an example, we can have dummy tests for the accessors.

**Comment by mlan080** [comment]
**Alex tasks**

- [ ] Mount volume so that you can change the code and have the changes reflected in the container 

- [ ] Make running your test as the default command in your Dockerfile  - add to CMD?

**Comment by mlan080** [comment]
Question: Can't run 2 spec files in /app at once to show 2 examples?

**Comment by mlan080** [comment]
https://github.com/mlan080/tea-shops/pull/16
