### ISSUE TITLE
Create the shops table

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#6]
Add a sequel migration to create `shops` table: https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc

Attributes:

- id (primary key)
- name (string)
- description (text) 

We can go to a simple approach:

- [x] Install `sequel` gem (add it to the `Gemfile` and build the docker image again)
- [x] Create a migration file like `db/migrations/001_create_shops.rb`
- [x] Create the migration code for `shops` table, e.g. https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc#a-basic-migration (for running the migration you have to find a way of connecting to the SQLite database)
- [x] We don't need a rake task for ruuning the migrations, we use `sequel` command line: https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc#running-migrations

Goal: Create table shops in sequel lite database

**Comment by mlan080** [comment]
Questions:

How do I connect to the SQLite database in my migration?

**Comment by mlan080** [comment]
**More tasks created for myself** 

- [ ] Add bash service to docker-compose file
- [ ] Add description as an attribute
