### ISSUE TITLE
Add create method to Shop model

### ISSUE THREAD

**Issue by lucasrenan** [mlan080/tea-shops#7]
Based on an instance of `Shop`, we should be able to call `#create` instance method and it will try to persist the object into the database (using sequel).

e.g.

```ruby
shop = Shop.new
shop.name = "Green tea cafe"
shop.create
```

**Task 2 from Lucas - Adding the description** 

- [x] Add a description instance method
- [x]  Create migration
- [x] Insert description into the database

**Comment by mlan080** [comment]
Question:
1. Where does this shop = Shop.new go? 
We can put it inside the Shop.rb but for testing, use helloworld.rb as it's already CMD in the Dockerfile
